feat: add page and logic for 404 errors
checkly/danube-store pull request #13
Opened 2023-05-08 19:02 UTC by nahuelon

Add `404` page and logic to the project. The `https://danube-webshop.herokuapp.com/` will be used as CLI checks examples under the `advances-project`.

2023-05-08 19:06 UTC, nahuelon commented
@ragog @tnolet , I found the project hosted in a Heroku instance but I don't know if there is a CI/CD flow to deploy it. Also, I added the `vue/dist` folder into the `.gitignore` file but maybe it's necessary to execute the `npm run build` locally and push all the bundle into the PR. I'll wait your comment. Thanks!

2023-05-08 19:06 UTC, tnolet commented
@ragog we will use danube going forward for check examples in CLI

2023-05-09 08:17 UTC, ragog requested changes
@nahuelon thanks for the PR, I requested a small change. You are right, we do not have a CI setup to properly deploy Danube atm - it's always been a one man project built locally until now. Happy to help change that, just lmk

2023-05-09 08:17 UTC, ragog commented on .gitignore
> +vue/dist
@nahuelon as you noted we'll probably want to not add this to the .gitignore as it will contain the static assets we end up serving

2023-05-09 13:22 UTC, nahuelon commented
Close PR since, we removed the `404 Not Found` browser check from the CLI examples. Maybe, we can tackle these adjustments later.

2023-05-09 13:22 UTC, closed without merging